version: 0.2

phases:
    install:
        runtime-versions:
            docker: 20
            python: 3.9
        commands:
            - echo "Installing dependencies"
            - pip install -r requirements.txt
            - apt-get install -y linux-modules-extra-$(uname -r)
            - apt install -y iproute2 build-essential can-utils
            - modprobe vcan || true
            - ip link add dev vcan0 type vcan
            - ip link set up vcan0

    pre_build:
        commands:
            - echo "Logging in to Amazon ECR"
            - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 236796666074.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

    build:
        commands:
            - echo "Building Docker images"
            - cd CAN/TailLamp
            - make docker-build-test
            - cd ../BreakPedal
            - make docker-build-test
            - echo "Tagging images"
            - docker tag tail-lamp-test:arm64 236796666074.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/tail-lamp-test:arm64
            - docker tag brake-pedal-test:arm64 236796666074.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/brake-pedal-test:arm64
            - echo "Pushing to ECR"
            - docker push 236796666074.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/tail-lamp-test:arm64
            - docker push 236796666074.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/brake-pedal-test:arm64

    post_build:
        commands:
            - echo "Running integration tests"
            - cd CAN/tests
            - docker run -d --net=host --cap-add=NET_ADMIN --cap-add=NET_RAW tail-lamp-test:arm64
            - docker run --rm --net=host -d 236796666074.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/tail-lamp-test:arm64
            - docker run --rm --net=host -d 236796666074.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/brake-pedal-test:arm64
            - pytest -v -s tests/integration-test.py

artifacts:
    files:
        - '**/*'
